build:
  maxIssues: 0

complexity:
  LongParameterList:
    active: true
    functionThreshold: 7
    constructorThreshold: 8
  LongMethod:
    active: true
    threshold: 60
  CyclomaticComplexMethod:
    active: true
    threshold: 15

style:
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignoreAnnotated:
      - 'Preview'
      - 'Composable'
  MaxLineLength:
    active: true
    maxLineLength: 120
  WildcardImport:
    active: true
    excludeImports:
      - 'kotlinx.coroutines.*'

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
    ignoreAnnotated:
      - 'Composable'
